### PR TITLE
dont throw if same component is registered twice

### PR DESCRIPTION
**Pull request by digitalkaoz**
thanks for this awesome di ;)

instead of throwing we should silently ignore it...

happens with jest

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Unfortunately its not that easy. If during runtime you have a component twice without notice it would be too hard to debug this and will result in issues here.
I would favor the following ways:
* some reset function which could be executed before or after a test
* a test mode which do not throw (still hard to debug in case of error)

What do you think?

**Comment by digitalkaoz** [comment]
i guess a `clear` function would help in other scenarios too.. PR welcome?

**Comment by KnisterPeter** [comment]
Yes, I think that could be helpful in more cases. To do not corrupt/mess with the scanner it would be best to create something like a 'snapshot' and a 'reset from snapshot'.
Currently the scanner-state is too tightly coupled to a new tsdi container.

**Comment by KnisterPeter** [comment]
I'll close this for now since it is resolved, isn't it?

**Pull request closed without merging**
